export class ACTIONS {
    static INIT = "INIT";
    static GET_PRODUCTS = "GET_PRODUCTS";
    static GET_PRODUCTS_DONE = "GET_PRODUCTS_DONE";
    static GET_CATEGORIES ="GET_CATEGORIES";
    static GET_CATEGORIES_DONE ="GET_CATEGORIES_DONE";
    static GET_PRODUCTS_BY_CATEGORY="GET_PRODUCTS_BY_CATEGORY";
    static GET_PRODUCTS_BY_CATEGORY_DONE="GET_PRODUCTS_BY_CATEGORY_DONE";
    static ADD_TO_CART="ADD_TO_CART";
    static ADD_TO_CART_DONE="ADD_TO_CART_DONE";
    static DEL_CART_ITEM="DEL_CART_ITEM";
    static DEL_CART_ITEM_DONE="DEL_CART_ITEM_DONE";
    static USER_LOGIN="USER_LOGIN";
    static USER_LOGIN_DONE="USER_LOGIN_DONE";
    static GET_CART_ITEMS="GET_CART_ITEMS";
    static GET_CART_ITEMS_DONE="GET_CART_ITEMS_DONE";
    static VERIFY_SESSION="VERIFY_SESSION";
    static LOGOUT="LOGOUT";
    static LOGOUT_DONE="LOGOUT_DONE";
    static REGISTER="REGISTER";
    static REGISTER_DONE="REGISTER_DONE";
    static DELETE_ALL_CARTITEMS="DELETE_ALL_CARTITEMS";
    static DELETE_ALL_CARTITEMS_DONE="DELETE_ALL_CARTITEMS_DONE";

    
}