export class ACTIONS {
    static INIT = "INIT";
    static GET_PRODUCTS = "GET_PRODUCTS";
    static GET_PRODUCTS_DONE = "GET_PRODUCTS_DONE";
    static GET_CATEGORIES ="GET_CATEGORIES";
    static GET_CATEGORIES_DONE ="GET_CATEGORIES_DONE";
    static GET_PRODUCTS_BY_CATEGORY="GET_PRODUCTS_BY_CATEGORY";
    static GET_PRODUCTS_BY_CATEGORY_DONE="GET_PRODUCTS_BY_CATEGORY_DONE";
    
}