import {
    init,
    getProducts,
    getProductsDone,
    getCategories,
    getCategoriesDone,
    getProductsByCategory,
    getProductsByCategoryDone,
    addToCart,
    addToCartDone,
    userLogin,
    userLoginDone,
    getCartItems,
    getCartItemsDone,
    delCartItem,
    delCartItemDone,
} from "./actions";

export const allActions ={
    init,
    getProducts,
    getProductsDone,
    getCategories,
    getCategoriesDone,
    getProductsByCategory,
    getProductsByCategoryDone,
    addToCart,
    addToCartDone,
    userLogin,
    userLoginDone,
    getCartItems,
    getCartItemsDone,
    delCartItem,
    delCartItemDone,

};